services:
  anaconda:  #環境変数
    build: .  # カレントフォルダーを「.」を書く。これによりDockerfileを使ってイメージが作成される。
    image: anaconda3
    ports:
      - "7777:8888"
    container_name: anaconda3
    working_dir: '/root/'
    tty: true
    volumes:
      - ./app:/usr/src/app